"""Initial tables creation

Revision ID: 1d058874a538
Revises: 
Create Date: 2026-08-12 15:44:26.259769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d058874a538'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    op.create_table('locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='위치 PK'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='상위 위치 ID'),
    sa.Column('location_code', sa.String(length=64), nullable=False, comment='위치 코드'),
    sa.Column('name', sa.String(length=150), nullable=False, comment='위치명'),
    sa.Column('location_type', sa.String(length=50), nullable=False, comment='위치 유형'),
    sa.Column('floor', sa.String(length=30), nullable=True, comment='층'),
    sa.Column('building', sa.String(length=100), nullable=True, comment='건물명'),
    sa.Column('description', sa.Text(), nullable=True, comment='설명'),
    sa.Column('x_coord', sa.Float(), nullable=True, comment='평면 X 좌표'),
    sa.Column('y_coord', sa.Float(), nullable=True, comment='평면 Y 좌표'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 시각'),
    sa.ForeignKeyConstraint(['parent_id'], ['locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_location_code'), 'locations', ['location_code'], unique=True)
    op.create_index(op.f('ix_locations_parent_id'), 'locations', ['parent_id'], unique=False)
    op.create_index('ix_locations_type_floor', 'locations', ['location_type', 'floor'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='내부 환자 PK'),
    sa.Column('patient_identifier', sa.String(length=64), nullable=False, comment='병원 환자 식별자'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='환자명'),
    sa.Column('birth_date', sa.Date(), nullable=True, comment='생년월일'),
    sa.Column('sex', sa.String(length=20), nullable=True, comment='성별'),
    sa.Column('phone_number', sa.String(length=30), nullable=True, comment='연락처'),
    sa.Column('address', sa.Text(), nullable=True, comment='주소'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 시각'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_patient_identifier'), 'patients', ['patient_identifier'], unique=True)
    op.create_table('sop_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='SOP 문서 PK'),
    sa.Column('document_code', sa.String(length=100), nullable=False, comment='문서 코드'),
    sa.Column('title', sa.String(length=300), nullable=False, comment='문서 제목'),
    sa.Column('disease_type', sa.String(length=100), nullable=True, comment='감염병 유형'),
    sa.Column('section', sa.String(length=200), nullable=True, comment='문서 섹션'),
    sa.Column('chunk_index', sa.Integer(), nullable=False, comment='청크 순번'),
    sa.Column('content', sa.Text(), nullable=False, comment='청크 본문'),
    sa.Column('source_path', sa.String(length=500), nullable=True, comment='원본 파일 경로'),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True, comment='문서 임베딩 벡터'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 시각'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sop_documents_disease_type'), 'sop_documents', ['disease_type'], unique=False)
    op.create_index('ix_sop_documents_doc_chunk', 'sop_documents', ['document_code', 'chunk_index'], unique=True)
    op.create_index(op.f('ix_sop_documents_document_code'), 'sop_documents', ['document_code'], unique=False)
    op.create_index('ix_sop_documents_embedding_hnsw', 'sop_documents', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('access_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='출입 로그 PK'),
    sa.Column('patient_id', sa.Integer(), nullable=False, comment='환자 ID'),
    sa.Column('location_id', sa.Integer(), nullable=False, comment='위치 ID'),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False, comment='출입 발생 시각'),
    sa.Column('event_type', sa.String(length=30), nullable=False, comment='이벤트 유형'),
    sa.Column('source_system', sa.String(length=100), nullable=True, comment='원천 시스템'),
    sa.Column('raw_payload', sa.Text(), nullable=True, comment='원본 로그'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_logs_location_id'), 'access_logs', ['location_id'], unique=False)
    op.create_index('ix_access_logs_location_time', 'access_logs', ['location_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_access_logs_occurred_at'), 'access_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_access_logs_patient_id'), 'access_logs', ['patient_id'], unique=False)
    op.create_index('ix_access_logs_patient_time', 'access_logs', ['patient_id', 'occurred_at'], unique=False)
    op.create_index('ix_access_logs_spacetime', 'access_logs', ['patient_id', 'location_id', 'occurred_at'], unique=False)
    op.create_table('emr_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='EMR PK'),
    sa.Column('patient_id', sa.Integer(), nullable=False, comment='환자 ID'),
    sa.Column('record_type', sa.String(length=50), nullable=False, comment='기록 유형'),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False, comment='기록 시각'),
    sa.Column('department', sa.String(length=100), nullable=True, comment='진료과'),
    sa.Column('diagnosis_code', sa.String(length=50), nullable=True, comment='진단 코드'),
    sa.Column('title', sa.String(length=200), nullable=True, comment='기록 제목'),
    sa.Column('content', sa.Text(), nullable=False, comment='기록 본문'),
    sa.Column('structured_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='구조화 EMR 데이터'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emr_records_diagnosis_code'), 'emr_records', ['diagnosis_code'], unique=False)
    op.create_index(op.f('ix_emr_records_patient_id'), 'emr_records', ['patient_id'], unique=False)
    op.create_index('ix_emr_records_patient_recorded_at', 'emr_records', ['patient_id', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_emr_records_recorded_at'), 'emr_records', ['recorded_at'], unique=False)
    op.create_index('ix_emr_records_structured_data_gin', 'emr_records', ['structured_data'], unique=False, postgresql_using='gin')
    op.create_table('investigation_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='조사 결과 PK'),
    sa.Column('patient_id', sa.Integer(), nullable=False, comment='기준 환자 ID'),
    sa.Column('investigation_uid', sa.String(length=100), nullable=False, comment='조사 고유 ID'),
    sa.Column('disease_type', sa.String(length=100), nullable=False, comment='감염병 유형'),
    sa.Column('status', sa.String(length=30), nullable=False, comment='조사 상태'),
    sa.Column('risk_level', sa.String(length=30), nullable=True, comment='최종 위험도'),
    sa.Column('summary', sa.Text(), nullable=True, comment='조사 요약'),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='FHIR 참고 구조화 조사 결과'),
    sa.Column('evidence_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='근거 문서 및 판단 근거'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='오류 메시지'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 시각'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_results_disease_type'), 'investigation_results', ['disease_type'], unique=False)
    op.create_index('ix_investigation_results_evidence_json_gin', 'investigation_results', ['evidence_json'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_investigation_results_investigation_uid'), 'investigation_results', ['investigation_uid'], unique=True)
    op.create_index('ix_investigation_results_patient_created', 'investigation_results', ['patient_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_investigation_results_patient_id'), 'investigation_results', ['patient_id'], unique=False)
    op.create_index('ix_investigation_results_result_json_gin', 'investigation_results', ['result_json'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_investigation_results_risk_level'), 'investigation_results', ['risk_level'], unique=False)
    op.create_index(op.f('ix_investigation_results_status'), 'investigation_results', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investigation_results_status'), table_name='investigation_results')
    op.drop_index(op.f('ix_investigation_results_risk_level'), table_name='investigation_results')
    op.drop_index('ix_investigation_results_result_json_gin', table_name='investigation_results', postgresql_using='gin')
    op.drop_index(op.f('ix_investigation_results_patient_id'), table_name='investigation_results')
    op.drop_index('ix_investigation_results_patient_created', table_name='investigation_results')
    op.drop_index(op.f('ix_investigation_results_investigation_uid'), table_name='investigation_results')
    op.drop_index('ix_investigation_results_evidence_json_gin', table_name='investigation_results', postgresql_using='gin')
    op.drop_index(op.f('ix_investigation_results_disease_type'), table_name='investigation_results')
    op.drop_table('investigation_results')
    op.drop_index('ix_emr_records_structured_data_gin', table_name='emr_records', postgresql_using='gin')
    op.drop_index(op.f('ix_emr_records_recorded_at'), table_name='emr_records')
    op.drop_index('ix_emr_records_patient_recorded_at', table_name='emr_records')
    op.drop_index(op.f('ix_emr_records_patient_id'), table_name='emr_records')
    op.drop_index(op.f('ix_emr_records_diagnosis_code'), table_name='emr_records')
    op.drop_table('emr_records')
    op.drop_index('ix_access_logs_spacetime', table_name='access_logs')
    op.drop_index('ix_access_logs_patient_time', table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_patient_id'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_occurred_at'), table_name='access_logs')
    op.drop_index('ix_access_logs_location_time', table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_location_id'), table_name='access_logs')
    op.drop_table('access_logs')
    op.drop_index('ix_sop_documents_embedding_hnsw', table_name='sop_documents', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_sop_documents_document_code'), table_name='sop_documents')
    op.drop_index('ix_sop_documents_doc_chunk', table_name='sop_documents')
    op.drop_index(op.f('ix_sop_documents_disease_type'), table_name='sop_documents')
    op.drop_table('sop_documents')
    op.drop_index(op.f('ix_patients_patient_identifier'), table_name='patients')
    op.drop_table('patients')
    op.drop_index('ix_locations_type_floor', table_name='locations')
    op.drop_index(op.f('ix_locations_parent_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_location_code'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
