"""add source metadata to sop documents

Revision ID: 64f15a080959
Revises: 1d058874a538
Create Date: 2026-08-13 13:47:08.647417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '64f15a080959'
down_revision: Union[str, Sequence[str], None] = '1d058874a538'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sop_documents', sa.Column('source_type', sa.String(length=50), nullable=False, comment='문서 출처 유형'))
    op.add_column('sop_documents', sa.Column('authority', sa.String(length=100), nullable=True, comment='발행 기관'))
    op.add_column('sop_documents', sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='추가 메타데이터'))
    op.alter_column('sop_documents', 'id',
               existing_type=sa.INTEGER(),
               comment='지침서 PK',
               existing_comment='SOP 문서 PK',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sop_documents', 'source_path',
               existing_type=sa.VARCHAR(length=500),
               comment='원본 경로 또는 URL',
               existing_comment='원본 파일 경로',
               existing_nullable=True)
    op.alter_column('sop_documents', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               comment='임베딩 벡터',
               existing_comment='문서 임베딩 벡터',
               existing_nullable=True)
    op.create_index(op.f('ix_sop_documents_authority'), 'sop_documents', ['authority'], unique=False)
    op.create_index('ix_sop_documents_authority_disease', 'sop_documents', ['authority', 'disease_type'], unique=False)
    op.create_index('ix_sop_documents_metadata_json_gin', 'sop_documents', ['metadata_json'], unique=False, postgresql_using='gin')
    op.create_index('ix_sop_documents_source_disease', 'sop_documents', ['source_type', 'disease_type'], unique=False)
    op.create_index(op.f('ix_sop_documents_source_type'), 'sop_documents', ['source_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sop_documents_source_type'), table_name='sop_documents')
    op.drop_index('ix_sop_documents_source_disease', table_name='sop_documents')
    op.drop_index('ix_sop_documents_metadata_json_gin', table_name='sop_documents', postgresql_using='gin')
    op.drop_index('ix_sop_documents_authority_disease', table_name='sop_documents')
    op.drop_index(op.f('ix_sop_documents_authority'), table_name='sop_documents')
    op.alter_column('sop_documents', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               comment='문서 임베딩 벡터',
               existing_comment='임베딩 벡터',
               existing_nullable=True)
    op.alter_column('sop_documents', 'source_path',
               existing_type=sa.VARCHAR(length=500),
               comment='원본 파일 경로',
               existing_comment='원본 경로 또는 URL',
               existing_nullable=True)
    op.alter_column('sop_documents', 'id',
               existing_type=sa.INTEGER(),
               comment='SOP 문서 PK',
               existing_comment='지침서 PK',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('sop_documents', 'metadata_json')
    op.drop_column('sop_documents', 'authority')
    op.drop_column('sop_documents', 'source_type')
    # ### end Alembic commands ###
