"""add post action tracking tables

Revision ID: c7639e219383
Revises: c8748a383e2c
Create Date: 2026-08-20 10:50:22.751553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7639e219383'
down_revision: Union[str, Sequence[str], None] = 'c8748a383e2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='접촉자 케이스 PK'),
    sa.Column('index_patient_id', sa.Integer(), nullable=False, comment='기준 확진자 ID'),
    sa.Column('patient_id', sa.Integer(), nullable=False, comment='접촉자 환자 ID'),
    sa.Column('disease_type', sa.String(length=100), nullable=False, comment='감염병 유형'),
    sa.Column('contact_type', sa.String(length=100), nullable=True, comment='접촉 유형'),
    sa.Column('risk_level', sa.String(length=20), nullable=False, comment='위험도 HIGH/MEDIUM/LOW'),
    sa.Column('test_status', sa.String(length=30), server_default='RECOMMENDED', nullable=False, comment='검사 상태'),
    sa.Column('sms_sent_status', sa.String(length=30), server_default='PENDING', nullable=False, comment='문자 발송 상태'),
    sa.Column('monitoring_status', sa.String(length=30), server_default='ACTIVE', nullable=False, comment='모니터링 상태'),
    sa.Column('case_status', sa.String(length=30), server_default='OPEN', nullable=False, comment='케이스 상태'),
    sa.Column('reason', sa.Text(), nullable=True, comment='AI 위험도 판정 근거'),
    sa.Column('action_plan', sa.Text(), nullable=True, comment='권장 조치'),
    sa.Column('first_exposed_at', sa.DateTime(timezone=True), nullable=True, comment='최초 노출 시각'),
    sa.Column('last_exposed_at', sa.DateTime(timezone=True), nullable=True, comment='마지막 노출 시각'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 시각'),
    sa.ForeignKeyConstraint(['index_patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contact_cases_case_monitoring', 'contact_cases', ['case_status', 'monitoring_status'], unique=False)
    op.create_index(op.f('ix_contact_cases_case_status'), 'contact_cases', ['case_status'], unique=False)
    op.create_index(op.f('ix_contact_cases_contact_type'), 'contact_cases', ['contact_type'], unique=False)
    op.create_index(op.f('ix_contact_cases_disease_type'), 'contact_cases', ['disease_type'], unique=False)
    op.create_index(op.f('ix_contact_cases_first_exposed_at'), 'contact_cases', ['first_exposed_at'], unique=False)
    op.create_index('ix_contact_cases_index_patient_contact', 'contact_cases', ['index_patient_id', 'patient_id'], unique=False)
    op.create_index(op.f('ix_contact_cases_index_patient_id'), 'contact_cases', ['index_patient_id'], unique=False)
    op.create_index(op.f('ix_contact_cases_last_exposed_at'), 'contact_cases', ['last_exposed_at'], unique=False)
    op.create_index(op.f('ix_contact_cases_monitoring_status'), 'contact_cases', ['monitoring_status'], unique=False)
    op.create_index(op.f('ix_contact_cases_patient_id'), 'contact_cases', ['patient_id'], unique=False)
    op.create_index(op.f('ix_contact_cases_risk_level'), 'contact_cases', ['risk_level'], unique=False)
    op.create_index('ix_contact_cases_risk_test_sms', 'contact_cases', ['risk_level', 'test_status', 'sms_sent_status'], unique=False)
    op.create_index(op.f('ix_contact_cases_sms_sent_status'), 'contact_cases', ['sms_sent_status'], unique=False)
    op.create_index(op.f('ix_contact_cases_test_status'), 'contact_cases', ['test_status'], unique=False)
    op.create_table('lab_tests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='검사 기록 PK'),
    sa.Column('patient_id', sa.Integer(), nullable=False, comment='환자 ID'),
    sa.Column('test_date', sa.DateTime(timezone=True), nullable=False, comment='검사 일시'),
    sa.Column('test_type', sa.String(length=50), nullable=False, comment='검사 유형 PCR/RAT 등'),
    sa.Column('disease_type', sa.String(length=100), nullable=False, comment='감염병 유형'),
    sa.Column('result', sa.String(length=30), nullable=False, comment='검사 결과 PENDING/NEGATIVE/POSITIVE 등'),
    sa.Column('source_system', sa.String(length=100), server_default='SYNTHETIC', nullable=False, comment='검사 출처'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_tests_disease_type'), 'lab_tests', ['disease_type'], unique=False)
    op.create_index('ix_lab_tests_patient_disease_date', 'lab_tests', ['patient_id', 'disease_type', 'test_date'], unique=False)
    op.create_index(op.f('ix_lab_tests_patient_id'), 'lab_tests', ['patient_id'], unique=False)
    op.create_index('ix_lab_tests_patient_result', 'lab_tests', ['patient_id', 'result'], unique=False)
    op.create_index(op.f('ix_lab_tests_result'), 'lab_tests', ['result'], unique=False)
    op.create_index(op.f('ix_lab_tests_test_date'), 'lab_tests', ['test_date'], unique=False)
    op.create_index(op.f('ix_lab_tests_test_type'), 'lab_tests', ['test_type'], unique=False)
    op.create_table('vital_signs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='활력징후 PK'),
    sa.Column('patient_id', sa.Integer(), nullable=False, comment='환자 ID'),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False, comment='측정 시각'),
    sa.Column('temperature', sa.Float(), nullable=False, comment='체온'),
    sa.Column('source_system', sa.String(length=100), server_default='SYNTHETIC', nullable=False, comment='기록 출처'),
    sa.Column('note', sa.Text(), nullable=True, comment='증상 메모'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vital_signs_patient_id'), 'vital_signs', ['patient_id'], unique=False)
    op.create_index('ix_vital_signs_patient_recorded', 'vital_signs', ['patient_id', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_vital_signs_recorded_at'), 'vital_signs', ['recorded_at'], unique=False)
    op.create_index('ix_vital_signs_temperature_recorded', 'vital_signs', ['temperature', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vital_signs_temperature_recorded', table_name='vital_signs')
    op.drop_index(op.f('ix_vital_signs_recorded_at'), table_name='vital_signs')
    op.drop_index('ix_vital_signs_patient_recorded', table_name='vital_signs')
    op.drop_index(op.f('ix_vital_signs_patient_id'), table_name='vital_signs')
    op.drop_table('vital_signs')
    op.drop_index(op.f('ix_lab_tests_test_type'), table_name='lab_tests')
    op.drop_index(op.f('ix_lab_tests_test_date'), table_name='lab_tests')
    op.drop_index(op.f('ix_lab_tests_result'), table_name='lab_tests')
    op.drop_index('ix_lab_tests_patient_result', table_name='lab_tests')
    op.drop_index(op.f('ix_lab_tests_patient_id'), table_name='lab_tests')
    op.drop_index('ix_lab_tests_patient_disease_date', table_name='lab_tests')
    op.drop_index(op.f('ix_lab_tests_disease_type'), table_name='lab_tests')
    op.drop_table('lab_tests')
    op.drop_index(op.f('ix_contact_cases_test_status'), table_name='contact_cases')
    op.drop_index(op.f('ix_contact_cases_sms_sent_status'), table_name='contact_cases')
    op.drop_index('ix_contact_cases_risk_test_sms', table_name='contact_cases')
    op.drop_index(op.f('ix_contact_cases_risk_level'), table_name='contact_cases')
    op.drop_index(op.f('ix_contact_cases_patient_id'), table_name='contact_cases')
    op.drop_index(op.f('ix_contact_cases_monitoring_status'), table_name='contact_cases')
    op.drop_index(op.f('ix_contact_cases_last_exposed_at'), table_name='contact_cases')
    op.drop_index(op.f('ix_contact_cases_index_patient_id'), table_name='contact_cases')
    op.drop_index('ix_contact_cases_index_patient_contact', table_name='contact_cases')
    op.drop_index(op.f('ix_contact_cases_first_exposed_at'), table_name='contact_cases')
    op.drop_index(op.f('ix_contact_cases_disease_type'), table_name='contact_cases')
    op.drop_index(op.f('ix_contact_cases_contact_type'), table_name='contact_cases')
    op.drop_index(op.f('ix_contact_cases_case_status'), table_name='contact_cases')
    op.drop_index('ix_contact_cases_case_monitoring', table_name='contact_cases')
    op.drop_table('contact_cases')
    # ### end Alembic commands ###
