"""add synthetic data fields and bed assignments

Revision ID: c8748a383e2c
Revises: ac30b05c450d
Create Date: 2026-08-19 10:21:19.102682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8748a383e2c'
down_revision: Union[str, Sequence[str], None] = 'ac30b05c450d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bed_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='병상 배정 PK'),
    sa.Column('patient_id', sa.Integer(), nullable=False, comment='환자 ID'),
    sa.Column('location_id', sa.Integer(), nullable=False, comment='병실 위치 ID'),
    sa.Column('admitted_at', sa.DateTime(timezone=True), nullable=False, comment='입실 시각'),
    sa.Column('discharged_at', sa.DateTime(timezone=True), nullable=True, comment='퇴실 시각'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 시각'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bed_assignments_admitted_at'), 'bed_assignments', ['admitted_at'], unique=False)
    op.create_index(op.f('ix_bed_assignments_discharged_at'), 'bed_assignments', ['discharged_at'], unique=False)
    op.create_index(op.f('ix_bed_assignments_location_id'), 'bed_assignments', ['location_id'], unique=False)
    op.create_index('ix_bed_assignments_location_period', 'bed_assignments', ['location_id', 'admitted_at', 'discharged_at'], unique=False)
    op.create_index(op.f('ix_bed_assignments_patient_id'), 'bed_assignments', ['patient_id'], unique=False)
    op.create_index('ix_bed_assignments_patient_period', 'bed_assignments', ['patient_id', 'admitted_at', 'discharged_at'], unique=False)
    op.add_column('access_logs', sa.Column('direction', sa.String(length=10), nullable=False, comment='출입 방향'))
    op.alter_column('access_logs', 'occurred_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='출입 시각',
               existing_comment='출입 발생 시각',
               existing_nullable=False)
    op.create_index('ix_access_logs_location_direction_time', 'access_logs', ['location_id', 'direction', 'occurred_at'], unique=False)
    op.alter_column('locations', 'name',
               existing_type=sa.VARCHAR(length=150),
               comment='장소명',
               existing_comment='위치명',
               existing_nullable=False)
    op.alter_column('locations', 'floor',
               existing_type=sa.VARCHAR(length=30),
               comment='층수',
               existing_comment='층',
               existing_nullable=True)
    op.create_index('ix_locations_xy', 'locations', ['x_coord', 'y_coord'], unique=False)
    op.add_column('patients', sa.Column('age', sa.Integer(), nullable=True, comment='나이'))
    op.add_column('patients', sa.Column('current_diagnosis', sa.String(length=200), nullable=True, comment='현재 진단명'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'current_diagnosis')
    op.drop_column('patients', 'age')
    op.drop_index('ix_locations_xy', table_name='locations')
    op.alter_column('locations', 'floor',
               existing_type=sa.VARCHAR(length=30),
               comment='층',
               existing_comment='층수',
               existing_nullable=True)
    op.alter_column('locations', 'name',
               existing_type=sa.VARCHAR(length=150),
               comment='위치명',
               existing_comment='장소명',
               existing_nullable=False)
    op.drop_index('ix_access_logs_location_direction_time', table_name='access_logs')
    op.alter_column('access_logs', 'occurred_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='출입 발생 시각',
               existing_comment='출입 시각',
               existing_nullable=False)
    op.drop_column('access_logs', 'direction')
    op.drop_index('ix_bed_assignments_patient_period', table_name='bed_assignments')
    op.drop_index(op.f('ix_bed_assignments_patient_id'), table_name='bed_assignments')
    op.drop_index('ix_bed_assignments_location_period', table_name='bed_assignments')
    op.drop_index(op.f('ix_bed_assignments_location_id'), table_name='bed_assignments')
    op.drop_index(op.f('ix_bed_assignments_discharged_at'), table_name='bed_assignments')
    op.drop_index(op.f('ix_bed_assignments_admitted_at'), table_name='bed_assignments')
    op.drop_table('bed_assignments')
    # ### end Alembic commands ###
